name: Deploy to Remote Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into remote server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: root
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd /root/discord_bot/Brott
          git checkout master
          git pull
          poetry install
          tmux kill-session -t discord_brott || true 
          tmux new -d -s discord_brott
          tmux send-keys -t discord_brott "poetry run python bot.py" C-m
