name: Deploy to Remote Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH into remote server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: root
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          pkill -f bot.py
          cd /root/discord_bot/Brott
          git pull
          poetry install
          poetry run python bot.py
